### 匯入資料

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

df_train = pd.read_csv('covid.train.csv')

print( f'train {df_train.shape}' )
display( df_train.head() )

train (2699, 118)

,id,AL,AK,AZ,AR,CA,CO,CT,FL,GA,ID,IL,IN,IA,KS,KY,LA,MD,MA,MI,MN,MS,MO,NE,NV,NJ,NM,NY,NC,OH,OK,OR,RI,SC,TX,UT,VA,WA,cli,ili,hh_cmnty_cli,nohh_cmnty_cli,wearing_mask,travel_outside_state,work_outside_home,shop,restaurant,spent_time,large_event,public_transit,anxious,depressed,worried_finances,tested_positive,cli.1,ili.1,hh_cmnty_cli.1,nohh_cmnty_cli.1,wearing_mask.1,travel_outside_state.1,work_outside_home.1,shop.1,restaurant.1,spent_time.1,large_event.1,public_transit.1,anxious.1,depressed.1,worried_finances.1,tested_positive.1,cli.2,ili.2,hh_cmnty_cli.2,nohh_cmnty_cli.2,wearing_mask.2,travel_outside_state.2,work_outside_home.2,shop.2,restaurant.2,spent_time.2,large_event.2,public_transit.2,anxious.2,depressed.2,worried_finances.2,tested_positive.2,cli.3,ili.3,hh_cmnty_cli.3,nohh_cmnty_cli.3,wearing_mask.3,travel_outside_state.3,work_outside_home.3,shop.3,restaurant.3,spent_time.3,large_event.3,public_transit.3,anxious.3,depressed.3,worried_finances.3,tested_positive.3,cli.4,ili.4,hh_cmnty_cli.4,nohh_cmnty_cli.4,wearing_mask.4,travel_outside_state.4,work_outside_home.4,shop.4,restaurant.4,spent_time.4,large_event.4,public_transit.4,anxious.4,depressed.4,worried_finances.4,tested_positive.4
0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.658466,0.724606,12.939284,8.556230,76.521693,7.863621,33.069066,64.129378,33.438714,40.539878,17.446499,3.993190,10.122837,7.841023,37.992365,7.374846,0.653157,0.713249,12.488933,8.219380,75.179558,8.083434,32.564654,65.212903,34.285572,40.697210,17.754941,3.997443,10.161621,8.067275,37.882278,7.219989,0.677783,0.737965,12.487637,8.135510,74.189695,8.001016,32.145331,66.258549,34.931095,40.889258,18.038068,3.970457,10.043014,7.983358,37.705024,7.077938,0.666751,0.723506,12.367718,8.006131,73.211902,7.873342,31.330236,66.753902,35.586606,40.741650,17.800711,3.984791,10.148898,8.262288,37.384963,7.452243,0.685628,0.740943,12.364307,8.151578,71.820231,7.944531,31.113209,67.394551,36.674291,40.743132,17.842221,4.093712,10.440071,8.627117,37.329512,7.456154
1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.693287,0.675962,15.008467,11.091818,82.375469,11.082587,36.373964,60.471825,30.516978,43.162123,16.038761,4.519762,12.133287,10.155721,33.977549,9.850027,0.738029,0.720511,15.070049,10.990937,80.943299,10.596788,36.435828,61.653141,31.449290,43.751356,16.752518,4.385694,11.911724,9.798448,32.786802,10.050547,0.831586,0.827523,14.568504,10.578924,79.096391,10.418171,35.851804,62.835720,32.802637,43.753525,17.195922,4.671201,11.418314,10.600311,32.679030,10.388084,0.767643,0.763580,14.264862,10.212529,76.645984,10.614731,34.639961,63.652437,34.147714,44.682727,17.705140,4.938357,11.056725,10.889148,32.933142,8.707858,0.713255,0.719378,12.894363,8.919288,74.687112,10.523814,33.920257,64.398380,34.612238,44.035688,17.808103,4.924935,10.172662,9.954333,32.508881,8.010957
2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0.617041,0.617041,8.614719,5.238097,87.040999,15.569851,33.366362,58.819368,24.674416,36.678937,13.490946,6.639301,9.753290,7.691015,38.685771,3.897851,0.663597,0.635459,8.472831,5.154184,86.743467,15.915242,33.012910,60.157822,25.322821,36.456240,13.385945,6.700146,9.949982,7.833514,38.036480,3.083111,0.534394,0.497435,8.493353,5.125553,86.647289,15.963496,32.471093,60.910411,25.158967,35.968207,13.656070,6.748557,10.664876,7.975821,37.826924,3.132834,0.536224,0.498305,8.227657,5.298912,86.285798,15.788676,31.931642,61.233289,25.156025,36.032687,13.863302,6.879646,10.731187,7.847829,37.128714,3.444182,0.479111,0.432445,8.067909,5.333533,86.312419,16.477784,31.604604,62.101064,26.521875,36.746453,13.903667,7.313833,10.388712,7.956139,36.745588,2.906977
3,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.193768,1.272051,12.007656,7.219741,43.153686,20.972589,35.458649,69.833774,37.021123,48.022187,28.436903,4.083615,9.417865,9.385772,37.621189,10.297712,1.356577,1.432775,12.997184,7.843776,42.700646,21.298728,36.239612,68.768187,38.467655,47.910974,28.670073,3.656496,10.103152,8.703587,37.176198,9.280636,1.719706,1.690806,14.010509,9.008978,42.456657,21.733635,35.638084,67.990121,38.220482,48.231973,28.723417,3.808266,10.705132,8.735566,37.444261,12.146962,1.737550,1.709244,14.364735,9.096583,42.543746,20.206049,36.292271,67.319443,37.423946,47.738805,27.869656,3.409895,9.872694,8.413435,37.326366,13.404256,1.793346,1.766201,14.383789,9.416096,43.731591,19.140939,35.115738,67.935520,38.022492,48.434809,27.134876,3.101904,10.498683,8.231522,38.680162,12.575816
4,4,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1.455489,1.455489,20.957729,16.829163,28.556052,20.619196,34.824775,68.468540,38.046432,49.785967,23.441813,3.829427,10.988948,8.838078,29.949690,24.056627,1.298511,1.231606,20.189998,16.229791,28.650666,20.434643,35.616036,69.093886,38.079669,48.877583,23.150895,3.876591,11.312970,9.749943,30.663745,17.727289,1.486851,1.420611,20.160351,15.672487,29.314614,21.169727,35.821927,69.371958,38.419865,48.882435,23.988587,4.220540,11.872359,10.443728,29.898587,18.650809,1.373938,1.308346,20.103385,15.798003,29.985906,22.264955,35.265587,69.416544,38.580881,48.812327,23.377837,4.070402,11.349537,9.910033,29.375093,20.238111,1.264465,1.198567,20.257355,15.864201,30.613306,22.698218,35.129714,69.934592,38.242368,49.095933,22.683709,4.594620,9.878927,9.469290,28.344123,21.428589

### 欄位型態(Column Types)

In [2]:
# 定義判別欄位型態的函數
def Col_Types( Data ):
    Column_Types = Data.dtypes.to_frame().reset_index()   # 判別每個欄位的型態 
    Column_Types.columns = ['ColumnName','Type']
    Column_Types.sort_values( by='Type', inplace=True ) 
    return Column_Types
display( Col_Types(df_train) )

                 ColumnName     Type
0                        id    int64
21                       MS    int64
22                       MO    int64
23                       NE    int64
24                       NV    int64
..                      ...      ...
60      work_outside_home.1  float64
59   travel_outside_state.1  float64
116      worried_finances.4  float64
76      work_outside_home.2  float64
117       tested_positive.4  float64

[118 rows x 2 columns]

### 缺漏值(Missing Values)

In [3]:
# 定義用來統計欄位缺漏值總數的函數
def Missing_Counts( Data ) : 
    missing = Data.isnull().sum()  # 計算欄位中缺漏值的數量 
    missing = missing[ missing>0 ]
    missing.sort_values( inplace=True ) 
    
    Missing_Count = pd.DataFrame( { 'ColumnName':missing.index, 'MissingCount':missing.values } )  # Convert Series to DataFrame
    Missing_Count[ 'Percentage(%)' ] = Missing_Count['MissingCount'].apply( lambda x:round(x/Data.shape[0]*100,2) )
    return  Missing_Count
print( 'train :' )
display( Missing_Counts(df_train) )

train :

Empty DataFrame
Columns: [ColumnName, MissingCount, Percentage(%)]
Index: []

### 統計量(Statistic)

In [4]:
print( 'train' )
display( df_train.describe() )

train

,id,AL,AK,AZ,AR,CA,CO,CT,FL,GA,ID,IL,IN,IA,KS,KY,LA,MD,MA,MI,MN,MS,MO,NE,NV,NJ,NM,NY,NC,OH,OK,OR,RI,SC,TX,UT,VA,WA,cli,ili,hh_cmnty_cli,nohh_cmnty_cli,wearing_mask,travel_outside_state,work_outside_home,shop,restaurant,spent_time,large_event,public_transit,anxious,depressed,worried_finances,tested_positive,cli.1,ili.1,hh_cmnty_cli.1,nohh_cmnty_cli.1,wearing_mask.1,travel_outside_state.1,work_outside_home.1,shop.1,restaurant.1,spent_time.1,large_event.1,public_transit.1,anxious.1,depressed.1,worried_finances.1,tested_positive.1,cli.2,ili.2,hh_cmnty_cli.2,nohh_cmnty_cli.2,wearing_mask.2,travel_outside_state.2,work_outside_home.2,shop.2,restaurant.2,spent_time.2,large_event.2,public_transit.2,anxious.2,depressed.2,worried_finances.2,tested_positive.2,cli.3,ili.3,hh_cmnty_cli.3,nohh_cmnty_cli.3,wearing_mask.3,travel_outside_state.3,work_outside_home.3,shop.3,restaurant.3,spent_time.3,large_event.3,public_transit.3,anxious.3,depressed.3,worried_finances.3,tested_positive.3,cli.4,ili.4,hh_cmnty_cli.4,nohh_cmnty_cli.4,wearing_mask.4,travel_outside_state.4,work_outside_home.4,shop.4,restaurant.4,spent_time.4,large_event.4,public_transit.4,anxious.4,depressed.4,worried_finances.4,tested_positive.4
count,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000,2699.000000
mean,1349.170433,0.032234,0.022971,0.030011,0.028159,0.032975,0.022971,0.027047,0.022971,0.024824,0.022971,0.029270,0.033716,0.028900,0.025565,0.021860,0.027418,0.025936,0.029270,0.031864,0.032605,0.027788,0.027788,0.028900,0.024454,0.027047,0.025195,0.028900,0.022971,0.026306,0.029641,0.019637,0.024083,0.023342,0.022601,0.025936,0.030011,0.031864,0.929055,0.942800,15.139448,11.361719,51.846616,15.864961,33.084390,66.354204,34.673977,44.815813,19.923754,4.661624,11.895154,9.970230,34.827581,9.599680,0.935966,0.950077,15.227049,11.451188,51.619087,15.889132,33.063299,66.396445,34.721939,44.825616,19.951696,4.669599,11.914578,9.978714,34.827521,9.654780,0.943030,0.957383,15.314802,11.541271,51.403169,15.911573,33.045662,66.431178,34.761696,44.833368,19.978151,4.678452,11.933770,9.985709,34.825931,9.712005,0.950079,0.964578,15.407295,11.635973,51.207340,15.929914,33.030236,66.454623,34.794829,44.839698,19.998701,4.686318,11.947655,9.990279,34.825181,9.769782,0.956898,0.971633,15.504531,11.734277,51.024843,15.947624,33.019169,66.472173,34.825731,44.847642,20.021135,4.694451,11.963645,9.993727,34.830569,9.819307
std,779.523498,0.176654,0.149840,0.170649,0.165456,0.178605,0.149840,0.162251,0.149840,0.155617,0.149840,0.168594,0.180531,0.167555,0.157863,0.146253,0.163327,0.158972,0.168594,0.175670,0.177632,0.164396,0.164396,0.167555,0.154481,0.162251,0.156745,0.167555,0.149840,0.160073,0.169625,0.138775,0.153335,0.151015,0.148655,0.158972,0.170649,0.175670,0.500590,0.506881,8.188440,7.635697,16.041680,4.587564,3.797806,2.579895,4.250106,3.732372,3.618681,2.109780,2.222707,1.562551,3.583642,6.313452,0.504705,0.511091,8.257488,7.698325,15.770092,4.581852,3.803542,2.523895,4.193057,3.711097,3.578342,2.114107,2.234357,1.569038,3.588109,6.343652,0.509706,0.516230,8.323593,7.758770,15.510964,4.575176,3.810626,2.486977,4.144595,3.691246,3.541958,2.118587,2.247609,1.578923,3.597144,6.382100,0.514304,0.521070,8.390694,7.820468,15.268909,4.563894,3.819355,2.464644,4.101623,3.673111,3.507355,2.124118,2.258737,1.587661,3.604537,6.414908,0.518864,0.525888,8.454688,7.879511,15.045576,4.556996,3.829507,2.453508,4.068668,3.658667,3.480065,2.130388,2.270315,1.599229,3.613087,6.431729
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.212642,0.222141,5.980392,3.632015,18.873783,4.481132,24.560314,56.155790,21.160206,32.965636,9.144539,1.471465,7.347204,6.184896,24.591933,0.344828,0.212642,0.222141,5.980392,3.632015,18.873783,4.481132,24.560314,56.857707,21.684109,33.814227,9.144539,1.471465,7.347204,6.184896,24.591933,0.344828,0.212642,0.222141,5.980392,3.632015,18.873783,4.481132,24.560314,57.583599,21.930253,34.374998,9.369684,1.471465,7.347204,6.184896,24.591933,0.344828,0.212642,0.222141,5.980392,3.632015,18.873783,4.481132,24.560314,58.790906,22.229339,34.785784,9.369684,1.471465,7.347204,6.184896,24.591933,0.344828,0.212642,0.222141,5.980392,3.632015,18.873783,4.481132,24.560314,58.790906,22.229339,35.253253,9.811647,1.471465,7.347204,6.184896,24.591933,0.344828
25%,674.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.589220,0.593219,9.258142,6.131987,41.069359,13.015295,30.285241,64.698043,31.971361,42.304122,17.277796,3.381783,10.291517,8.807808,32.369819,4.861112,0.593299,0.595611,9.271706,6.150267,41.089576,13.054480,30.274052,64.755013,32.033966,42.333963,17.363391,3.382805,10.291517,8.809188,32.370283,4.887205,0.595167,0.597011,9.274822,6.155483,41.108457,13.067704,30.262261,64.819823,32.079453,42.346407,17.398901,3.384297,10.291517,8.808445,32.363206,4.902017,0.597007,0.597665,9.279137,6.163288,41.134205,13.099381,30.250773,64.864621,32.126825,42.346407,17.446419,3.383806,10.289697,8.807808,32.363206,4.924242,0.599321,0.599429,9.287108,6.167789,41.142616,13.110988,30.231124,64.878002,32.155400,42.346407,17.479073,3.382805,10.289697,8.803497,32.356108,4.928581
50%,1349.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.761953,0.775592,11.846534,7.883439,49.173725,15.768793,32.898929,66.670223,34.951308,45.210728,20.379799,4.237955,11.317122,9.713376,34.255348,7.502484,0.767922,0.780531,11.859409,7.903294,49.076562,15.783135,32.868335,66.693296,34.984448,45.203349,20.401471,4.250198,11.337143,9.723388,34.255052,7.523642,0.774126,0.785241,11.868658,7.919253,48.986473,15.797081,32.837158,66.694844,35.002005,45.203349,20.415732,4.257824,11.353442,9.738070,34.250481,7.543103,0.779292,0.789934,11.869500,7.944313,48.871729,15.813267,32.819722,66.694844,35.052852,45.203349,20.420670,4.273011,11.360853,9.749547,34.252328,7.589265,0.783340,0.794960,11.898464,7.988167,48.763167,15.822605,32.774245,66.702427,35.055289,45.187886,20.432378,4.287390,11.383425,9.757942,34.258832,7.670341
75%,2023.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.135863,1.152989,18.903221,14.799608,63.125921,18.722788,35.700040,68.228059,37.874535,47.648541,22.572231,5.308890,13.074735,10.973811,37.094330,13.316425,1.150706,1.161638,19.150490,15.170271,62.619747,18.747731,35.692000,68.232378,37.882290,47.622268,22.557963,5.317356,13.106606,10.990519,37.079855,13.455759,1.161798,1.175944,19.493509,15.381607,62.032329,18.764182,35.665183,68.233840,37.875962,47.615841,22.552527,5.329133,13.141667,11.000632,37.071200,13.573970,1.178348,1.194376,19.732328,15.616645,61.576315,18.801860,35.625804,68.239647,37.875962,47.606441,22.533346,5.343331,13.180543,11.007407,37.049475,13.740370,1.191353,1.202524,20.129915,15.820757,61.122932,18.824318,35.620394,68.243282,37.889341,47.605144,22.523629,5.363878,13.212067,11.022503,37.040154,13.841567
max,2699.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.139514,3.147406,42.132316,36.734787,89.817044,33.027876,44.571959,72.053180,44.230829,53.711318,31.294647,15.684276,19.618115,15.125404,45.522378,30.304636,3.139514,3.147406,42.132316,36.734787,89.108187,33.027876,44.571959,72.053180,44.230829,53.711318,31.294647,15.684276,19.618115,15.125404,45.522378,30.304636,3.139514,3.147406,42.132316,36.734787,87.946918,33.027876,44.571959,72.053180,44.314381,53.711318,31.294647,15.684276,19.618115,15.125404,45.522378,30.304636,3.139514,3.147406,42.132316,36.734787,87.789159,33.027876,44.571959,72.053180,44.314381,53.711318,31.294647,15.684276,19.618115,15.125404,45.522378,30.304636,3.201974,3.201974,42.132316,36.734787,87.642802,33.027876,44.571959,72.606926,44.314381,53.711318,31.294647,15.684276,19.618115,15.676377,45.522378,30.304636

### 資料分析(Data Analysis)

In [5]:
df_data = df_train
Survived_Counts = df_data['tested_positive.4'].value_counts().reset_index()
Survived_Counts.columns = ['tested_positive.4','Counts']
Survived_Counts

      tested_positive.4  Counts
0              4.861112       2
1              2.397260       2
2              6.000005       2
3              8.606557       2
4             18.911682       2
...                 ...     ...
2662           8.333361       1
2663          12.647059       1
2664           5.433070       1
2665           4.738531       1
2666          11.069423       1

[2667 rows x 2 columns]

### 相關係數(Correlation)

In [6]:
# positive 與其他欄位間的相關係數
Corr_Matrix = df_train.corr()  # 計算相關係數
Corr = Corr_Matrix.loc['tested_positive.4',:].sort_values()[:-1]
Corr = pd.DataFrame({ 'tested_positive.4':Corr })
# Corr.tail(50)
Corr.head(50)

                        tested_positive.4
public_transit.4                -0.415122
public_transit.3                -0.411625
public_transit.2                -0.408784
public_transit.1                -0.405867
public_transit                  -0.402255
shop.4                          -0.378931
shop.3                          -0.363074
shop.2                          -0.342185
shop.1                          -0.318763
shop                            -0.290625
MA                              -0.176164
CT                              -0.170920
NY                              -0.167147
NJ                              -0.159119
MD                              -0.142731
wearing_mask                    -0.135891
restaurant.4                    -0.121319
VA                              -0.118604
MN                              -0.112628
wearing_mask.1                  -0.111869
CA                              -0.111194
MI                              -0.105494
restaurant.3                    -0.105277
travel_outside_state.4          -0.104898
IL                              -0.101530
travel_outside_state.3          -0.094845
WA                              -0.092494
OR                              -0.088205
restaurant.2                    -0.087925
wearing_mask.2                  -0.087302
travel_outside_state.2          -0.085217
RI                              -0.084508
OH                              -0.082681
SC                              -0.077771
travel_outside_state.1          -0.075109
restaurant.1                    -0.069823
KY                              -0.069191
TX                              -0.068835
CO                              -0.068444
travel_outside_state            -0.064729
wearing_mask.3                  -0.062406
GA                              -0.060844
NM                              -0.057569
NC                              -0.052967
restaurant                      -0.048994
FL                              -0.047950
wearing_mask.4                  -0.037205
AZ                              -0.023748
IN                              -0.010755
spent_time.4                     0.026965

In [12]:
cols = Corr[-24:].index.tolist()
cols

['cli',
 'ili',
 'cli.1',
 'ili.1',
 'cli.2',
 'ili.2',
 'cli.3',
 'ili.3',
 'cli.4',
 'ili.4',
 'nohh_cmnty_cli',
 'nohh_cmnty_cli.1',
 'hh_cmnty_cli',
 'nohh_cmnty_cli.2',
 'hh_cmnty_cli.1',
 'nohh_cmnty_cli.3',
 'hh_cmnty_cli.2',
 'nohh_cmnty_cli.4',
 'hh_cmnty_cli.3',
 'hh_cmnty_cli.4',
 'tested_positive',
 'tested_positive.1',
 'tested_positive.2',
 'tested_positive.3']

In [13]:
print([df_train.columns.get_loc(c) for c in cols if c in df_train])

[38, 39, 54, 55, 70, 71, 86, 87, 102, 103, 41, 57, 40, 73, 56, 89, 72, 105, 88, 104, 53, 69, 85, 101]